name: "Main"

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
    tags-ignore:
      - '**'

jobs:
  analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Flutter with exact version
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.13.0"

      - name: Install dependencies
        run: flutter pub get

      - name: Run analyzer
        run: flutter analyze --fatal-warnings --fatal-infos .

      - name: Run formatter
        run: dart format -l 100 --set-exit-if-changed .


  testing:
    needs: analysis
    uses: surfstudio/flutter-ci-workflows/.github/workflows/testing.yml@main
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
    with:
      flutter-version: "3.13.0"
