name: "Main"

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
    tags-ignore:
      - '**'

jobs:
  analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Flutter with exact version
        if: ${{ inputs.flutter-version != ''}}
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.13.0"

      - name: Content
        id: check_files
        uses: andstor/file-existence-action@v1
        with:
          files: "LICENSE, README.md, example, CHANGELOG.md, CONTRIBUTING.md"

      - name: Install dependencies
        run: flutter pub get

      - name: Run dependency validator
        run: |
          dart pub global activate dependency_validator
          dart pub global run dependency_validator:dependency_validator

      - name: Run analyzer
        run: flutter analyze --fatal-warnings --fatal-infos .

      - name: Run formatter
        run: dart format -l 100 --set-exit-if-changed .

      - name: Run package analyzer
        uses: axel-op/dart-package-analyzer@v3
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}

  testing:
    needs: analysis
    uses: surfstudio/flutter-ci-workflows/.github/workflows/testing.yml@main
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
    with:
      flutter-version: "3.13.0"
