name: "Main"

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
    tags-ignore:
      - '**'

jobs:
  get_fvm_version:
    outputs:
      flutter_version: ${{ steps.fvm_version.outputs.flutterSdkVersion }}
    name: "Get Flutter version from FVM"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - id: fvm_version
        uses: zoexx/github-action-json-file-properties@release
        with:
          file_path: ".fvm/fvm_config.json"

  analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Flutter with exact version
        if: ${{ inputs.flutter-version != ''}}
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ needs.get_fvm_version.outputs.flutter_version }}

      - name: Install Flutter from Stable branch
        if: ${{ inputs.flutter-version == ''}}
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      - name: Content
        id: check_files
        uses: andstor/file-existence-action@v1
        with:
          files: "LICENSE, README.md, example, CHANGELOG.md, CONTRIBUTING.md"

      - name: File exists
        if: steps.check_files.outputs.files_exists == 'true'
        run: echo Content is ok!

      - name: Check Description
        run: echo | grep -q Description README.md ; echo $?

      - name: Check Example
        run: echo | grep -q Example README.md ; echo $?

      - name: Check Installation
        run: echo | grep -q Installation README.md ; echo $?

      - name: Install dependencies
        run: flutter pub get

      - name: Run dependency validator
        run: |
          dart pub global activate dependency_validator
          dart pub global run dependency_validator:dependency_validator

      - name: Run analyzer
        run: flutter analyze --fatal-warnings --fatal-infos .

      - name: Run formatter
        run: dart format --set-exit-if-changed .

      - name: Run package analyzer
        uses: axel-op/dart-package-analyzer@v3
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}

  testing:
    needs: [analysis, get_fvm_version]
    uses: surfstudio/flutter-ci-workflows/.github/workflows/testing.yml@main
    with:
      flutter-version: ${{ needs.get_fvm_version.outputs.flutter_version }}
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  build_android:
    needs: [ get_fvm_version, analysis ]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: "17"

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ needs.get_fvm_version.outputs.flutter_version }}

      - name: Get dependencies
        run: flutter pub get

      - name: Start release build
        run: flutter build appbundle

  build_ios_example:
    needs: [ get_fvm_version, analysis ]
    uses: surfstudio/flutter-ci-workflows/.github/workflows/build_ios_example.yml@main
    with:
      flutter-version: ${{ needs.get_fvm_version.outputs.flutter_version }}
